<!DOCTYPE html>
<html>
  <head>
    <title>Reply for iOS</title>

    <!-- Viewport mobile tag for sensible mobile support -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    {% block custom_scripts %}
    {% endblock custom_scripts %}
    <script src="/assets/js/main.js"></script>



  </head>

  <body>

    {% block header %}
      <h1>reply for iOS</h1>
    {% endblock header %}

    {% block content %}
    {% endblock content %}

    {% block footer %}
      <ul>
        <li>download now</li>
      </ul>
    {% endblock footer %}


  </body>
</html>
